
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class Bloodtype extends javax.swing.JFrame {

    /**
     * Creates new form Bloodtype
     */
    public Bloodtype() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GB1 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        RB6 = new javax.swing.JRadioButton();
        RB7 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        B1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        B1.setText("BACK TO HOME");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1);
        B1.setBounds(160, 380, 305, 84);

        L1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 255, 51));
        L1.setText("BLOOD TYPE");
        jPanel1.add(L1);
        L1.setBounds(190, 60, 221, 100);

        buttonGroup1.add(RB1);
        RB1.setText("A+");
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });
        jPanel1.add(RB1);
        RB1.setBounds(580, 43, 45, 25);

        buttonGroup1.add(RB2);
        RB2.setText("B+");
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });
        jPanel1.add(RB2);
        RB2.setBounds(580, 86, 43, 25);

        buttonGroup1.add(RB3);
        RB3.setText("AB+");
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });
        jPanel1.add(RB3);
        RB3.setBounds(580, 129, 51, 25);

        buttonGroup1.add(RB4);
        RB4.setText("AB-");
        RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB4ActionPerformed(evt);
            }
        });
        jPanel1.add(RB4);
        RB4.setBounds(582, 172, 49, 25);

        buttonGroup1.add(RB5);
        RB5.setText("O+");
        RB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB5ActionPerformed(evt);
            }
        });
        jPanel1.add(RB5);
        RB5.setBounds(582, 215, 45, 25);

        buttonGroup1.add(RB6);
        RB6.setText("O-");
        RB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB6ActionPerformed(evt);
            }
        });
        jPanel1.add(RB6);
        RB6.setBounds(584, 258, 43, 25);

        buttonGroup1.add(RB7);
        RB7.setText("A-");
        RB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB7ActionPerformed(evt);
            }
        });
        jPanel1.add(RB7);
        RB7.setBounds(584, 301, 41, 25);

        buttonGroup1.add(RB8);
        RB8.setText("B-");
        RB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB8ActionPerformed(evt);
            }
        });
        jPanel1.add(RB8);
        RB8.setBounds(584, 344, 41, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubham singh\\Desktop\\images.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, -4, 1000, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        HOME a=new HOME();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B1ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
        // TODO add your handling code here:
        if(RB1.isSelected())
        {
            JOptionPane.showMessageDialog(this,"Blood group A individuals have the A antigen on the surface of their RBCs, and blood serum containing IgM antibodies against the B antigen. Therefore, a group A individual can receive blood only from individuals of groups A or O (with A being preferable), and can donate blood to individuals with type A or AB.");
        }
    }//GEN-LAST:event_RB1ActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
        // TODO add your handling code here:
         if(RB2.isSelected())
        {
            JOptionPane.showMessageDialog(this,"Blood group B individuals have the B antigen on the surface of their RBCs, and blood serum containing IgM antibodies against the A antigen. Therefore, a group B individual can receive blood only from individuals of groups B or O (with B being preferable), and can donate blood to individuals with type B or AB.");
        }
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
        // TODO add your handling code here:
        if(RB3.isSelected())
        {
            JOptionPane.showMessageDialog(this,"Blood group AB individuals have both A and B antigens on the surface of their RBCs, and their blood plasma does not contain any antibodies against either A or B antigen. Therefore, an individual with type AB blood can receive blood from any group (with AB being preferable), but cannot donate blood to any group other than AB. They are known as universal recipients.");
        }
        
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB4ActionPerformed
        // TODO add your handling code here:
        if(RB4.isSelected())
        {
            JOptionPane.showMessageDialog(this,"blood group ab- is of rare type and found with difficulty");
        }
    }//GEN-LAST:event_RB4ActionPerformed

    private void RB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB5ActionPerformed
        // TODO add your handling code here:
        if(RB5.isSelected())
        {
            JOptionPane.showMessageDialog(this,"Therefore, a group O individual can receive blood only from a group O individual, but can donate blood to individuals of any ABO blood group (i.e., A, B, O or AB)");
        }
    }//GEN-LAST:event_RB5ActionPerformed

    private void RB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB6ActionPerformed
        // TODO add your handling code here:
        if(RB6.isSelected())
        {
            JOptionPane.showMessageDialog(this,"O Negative. As an O Negative blood donor you have a particularly unique opportunity to help people in emergency situations. O Negative blood cells are called “universal”");
        }
    }//GEN-LAST:event_RB6ActionPerformed

    private void RB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB7ActionPerformed
        // TODO add your handling code here:
        if(RB7.isSelected())
        {
            JOptionPane.showMessageDialog(this," A- Blood is Important A Negative. Only 6.3% of the population has A Negative blood. ...");
        }
    }//GEN-LAST:event_RB7ActionPerformed

    private void RB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB8ActionPerformed
        // TODO add your handling code here:
        if(RB8.isSelected())
        {
            JOptionPane.showMessageDialog(this,"s a B Negative blood donor, you are unique due to the rarity of your blood. Because your blood is rare, it is important to maintain sufficient supplies for our community ");
        }
    }//GEN-LAST:event_RB8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bloodtype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bloodtype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bloodtype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bloodtype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bloodtype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.ButtonGroup GB1;
    private javax.swing.JLabel L1;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
