
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class bloodcamp extends javax.swing.JFrame {

    /**
     * Creates new form bloodcamp
     */
    public bloodcamp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        L8 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        L7 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        L6 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox<>();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        TF1 = new javax.swing.JTextField();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        B1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B1.setText("SUBMIT");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1);
        B1.setBounds(300, 380, 129, 37);

        B2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        B2.setText("HOME");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2);
        B2.setBounds(900, 460, 97, 37);

        L8.setText("PHONE NO.");
        jPanel1.add(L8);
        L8.setBounds(575, 296, 64, 16);
        jPanel1.add(TF5);
        TF5.setBounds(761, 293, 211, 22);
        jPanel1.add(TF4);
        TF4.setBounds(761, 229, 211, 22);

        L7.setText("NO. OF PEPOLE VISITING ");
        jPanel1.add(L7);
        L7.setBounds(575, 232, 148, 16);
        jPanel1.add(TF2);
        TF2.setBounds(760, 160, 211, 22);

        L6.setText("VENUE");
        jPanel1.add(L6);
        L6.setBounds(580, 160, 148, 16);

        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGRA", "BARELLI", "DEOGARH", "ETAWAH", "FATEHPUR", "GR.NOIDA", "GHAZIABAD", "HAPUR", "JANSHI", "KANPUR", "LUCKNOW", "VARANSHI", " " }));
        jPanel1.add(CB1);
        CB1.setBounds(240, 310, 93, 22);

        L5.setText("CITY");
        jPanel1.add(L5);
        L5.setBounds(70, 300, 55, 16);

        L4.setText("EMAIL ID");
        jPanel1.add(L4);
        L4.setBounds(70, 230, 51, 16);
        jPanel1.add(TF3);
        TF3.setBounds(230, 230, 293, 22);

        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });
        jPanel1.add(TF1);
        TF1.setBounds(230, 160, 241, 22);

        L3.setText("NAME");
        jPanel1.add(L3);
        L3.setBounds(70, 160, 33, 16);

        L2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L2.setForeground(new java.awt.Color(102, 255, 102));
        L2.setText("IF YOU WANT TO ORGANIZE A BLOOD CAMP THEN FILL THE FORM BELOW-");
        jPanel1.add(L2);
        L2.setBounds(80, 80, 710, 31);

        L1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(0, 255, 0));
        L1.setText("BLOOD CAMP ORGANIZATION");
        jPanel1.add(L1);
        L1.setBounds(270, 20, 560, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubham singh\\Desktop\\donate blood save life_blood donation poster.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, 0, 1020, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        try{
            int nop,city;
            nop = Integer.parseInt(TF4.getText());
            if(CB1.getSelectedIndex()==0)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
            else if(CB1.getSelectedIndex()==1)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==2)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==3)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==4)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==5)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==6)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==7)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==8)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==9)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==10)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
             else if(CB1.getSelectedIndex()==11)
                JOptionPane.showMessageDialog(this,CB1.getSelectedItem()+"");
            
            Class.forName("java.sql.Driver");
            String database="jdbc:mysql://localhost:3306/Bloodbank";
            Connection con=DriverManager.getConnection(database,"root","11111996");
            Statement stmt=con.createStatement();
            String sql="insert into Bloodcamp values( '"+TF1.getText()+"',"+
                    nop+",'"+TF2.getText()+"','"+TF3.getText()+"','"
                    +TF5.getText()+"')";
            stmt.executeUpdate(sql);
            
               stmt.close();
               con.close();
               
        }
        catch(Exception e)
            
        {JOptionPane.showMessageDialog(null,""+e);
            
            
            
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        HOME a=new HOME();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B2ActionPerformed

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloodcamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloodcamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloodcamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloodcamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloodcamp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
