
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class Blooddonar extends javax.swing.JFrame {

    /**
     * Creates new form Blooddonar
     */
    public Blooddonar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        TF5 = new javax.swing.JTextField();
        L7 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        TF1 = new javax.swing.JTextField();
        L6 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 410, 103, 37);

        B2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B2.setText("HOME");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2);
        B2.setBounds(760, 440, 108, 38);
        jPanel1.add(TF5);
        TF5.setBounds(620, 290, 175, 22);

        L7.setText("AGE");
        jPanel1.add(L7);
        L7.setBounds(530, 290, 23, 16);

        L5.setText("phone no.");
        jPanel1.add(L5);
        L5.setBounds(520, 220, 57, 16);
        jPanel1.add(TF4);
        TF4.setBounds(620, 220, 175, 22);
        jPanel1.add(TF2);
        TF2.setBounds(220, 290, 156, 22);
        jPanel1.add(TF3);
        TF3.setBounds(220, 210, 156, 22);
        jPanel1.add(TF1);
        TF1.setBounds(220, 130, 368, 22);

        L6.setText("BLOOD TYPE");
        jPanel1.add(L6);
        L6.setBounds(110, 290, 72, 16);

        L4.setText("Address");
        jPanel1.add(L4);
        L4.setBounds(110, 210, 46, 16);

        L2.setText("Name");
        jPanel1.add(L2);
        L2.setBounds(110, 140, 33, 16);

        L1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L1.setText("BLOOD DONAR ");
        jPanel1.add(L1);
        L1.setBounds(490, 40, 186, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubham singh\\Desktop\\thumb-350-565095.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, -4, 1130, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int age;
            age = Integer.parseInt(TF5.getText());
            
            Class.forName("java.sql.Driver");
            String database="jdbc:mysql://localhost:3306/Bloodbank";
            Connection con=DriverManager.getConnection(database,"root","11111996");
            Statement stmt=con.createStatement();
            String sql="insert into Blooddonar values( '"+TF1.getText()+"',"+
                    age+",'"+TF2.getText()+"','"+TF3.getText()+"','"
                    +TF4.getText()+"')";
            stmt.executeUpdate(sql);
            
               stmt.close();
               con.close();
               
        }
        catch(Exception e)
            
        {JOptionPane.showMessageDialog(null,""+e);
        
        
            
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        HOME a=new HOME();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blooddonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blooddonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blooddonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blooddonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blooddonar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
