import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TF4 = new javax.swing.JTextField();
        TF5 = new javax.swing.JTextField();
        L9 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        TF1 = new javax.swing.JTextField();
        L8 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        L2 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        TF8 = new javax.swing.JTextField();
        TF7 = new javax.swing.JTextField();
        TF6 = new javax.swing.JPasswordField();
        L5 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(TF4);
        TF4.setBounds(806, 208, 186, 22);
        jPanel1.add(TF5);
        TF5.setBounds(803, 289, 153, 22);

        L9.setText("GENDER");
        jPanel1.add(L9);
        L9.setBounds(806, 427, 46, 16);

        RB1.setText("Male");
        jPanel1.add(RB1);
        RB1.setBounds(797, 475, 55, 25);

        RB2.setText("Female");
        jPanel1.add(RB2);
        RB2.setBounds(797, 516, 71, 25);
        jPanel1.add(TF1);
        TF1.setBounds(387, 120, 289, 22);

        L8.setText("MOBILE NO.");
        jPanel1.add(L8);
        L8.setBounds(653, 292, 68, 16);

        L7.setText("AGE");
        jPanel1.add(L7);
        L7.setBounds(653, 211, 70, 16);

        L1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 51, 51));
        L1.setText("REGISTER PAGE");
        jPanel1.add(L1);
        L1.setBounds(426, 25, 259, 44);

        B2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        B2.setText("HOME");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2);
        B2.setBounds(896, 579, 127, 63);

        L2.setText("FULL NAME");
        jPanel1.add(L2);
        L2.setBounds(182, 123, 64, 16);
        jPanel1.add(TF3);
        TF3.setBounds(387, 208, 150, 22);
        jPanel1.add(TF8);
        TF8.setBounds(387, 294, 150, 22);
        jPanel1.add(TF7);
        TF7.setBounds(273, 424, 248, 22);
        jPanel1.add(TF6);
        TF6.setBounds(273, 476, 248, 22);

        L5.setText("Password");
        jPanel1.add(L5);
        L5.setBounds(181, 479, 80, 16);

        L10.setText("Id");
        jPanel1.add(L10);
        L10.setBounds(191, 427, 55, 16);

        B1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        B1.setText("REGISTER");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1);
        B1.setBounds(293, 589, 195, 53);

        L3.setText("ADDRESS");
        jPanel1.add(L3);
        L3.setBounds(182, 211, 55, 16);

        L4.setText("BLOOD GROUP");
        jPanel1.add(L4);
        L4.setBounds(182, 297, 83, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubham singh\\Desktop\\register.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, -4, 1090, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        HOME a=new HOME();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        try{
            int age;
            age = Integer.parseInt(TF4.getText());
            char Gender='M';
            if(RB2.isSelected())
                Gender='F';
            Class.forName("java.sql.Driver");
            String database="jdbc:mysql://localhost:3306/Bloodbank";
            Connection con=DriverManager.getConnection(database,"root","11111996");
            Statement stmt=con.createStatement();
            String sql="insert into Register values( '"+TF1.getText()+"',"+
                    age+",'"+TF3.getText()+"','"+Gender+"','"+TF5.getText()+"','"+TF8.getText()+"','"
                    +TF7.getText()+"')";
            stmt.executeUpdate(sql);
           
             sql="insert into Bloodbank values("+TF7.getText()+"','"+TF6.getText()
                     +"')";
               stmt.executeUpdate(sql);
               stmt.close();
               con.close();
               new Bloodbank (TF7.getText()).setVisible(true);
               this.setVisible(false);
        }
        catch(Exception e)
            
        {JOptionPane.showMessageDialog(null,""+e);
            
            
            
        }
    }//GEN-LAST:event_B1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JPasswordField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
